version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: newspilot-postgres
    restart: always
    environment:
      POSTGRES_DB: newspilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
